### ISSUE TITLE
"Cannot invoke "net.minecraft.class_312.method_1610()" because "this.field_1729" is null"

### ISSUE THREAD

**Issue by Scarlaid** [MehVahdJukaar/FastPaintings#1]
![image](https://github.com/MehVahdJukaar/FastPaintings/assets/90851437/a415c1c3-5124-4962-a4e6-b7da88e8205c)

It doesn't say what specific causing the crash
My log: https://mclo.gs/xdwtUoF

**Comment by MehVahdJukaar** [comment]
You are on 1.19.4

**Comment by Scarlaid** [comment]
so why modrinth mark it as 1.19.2 - 1.19.4

**Comment by Scarlaid** [comment]
It is still the same
![image](https://github.com/MehVahdJukaar/FastPaintings/assets/90851437/beb1eab5-9537-4cf0-ae02-c8edba516417)

**Comment by Scarlaid** [comment]
reverted back to 1.0.0, still getting the same issue
![image](https://github.com/MehVahdJukaar/FastPaintings/assets/90851437/774e1056-55d4-4754-b0fb-e841cbd35241)

My log: https://mclo.gs/P4R1rMk

**Comment by MehVahdJukaar** [comment]
Ah modrinth seems to have marked it as 1.19.4 when it's not. Indact should only have happened with the first file which was uploaded manually

**Comment by Scarlaid** [comment]
so will this ever for 1,19,4 or this is already a fixed issue for 1.19.4

or you are taking time, because if it is then alright 🗿

**Comment by MehVahdJukaar** [comment]
Hm maybe it it gets more popular. For now 1.20 and 1.19.2 remain the main modding versions and I'm starting to abandon 1.19.2 too

**Comment by Scarlaid** [comment]
how about now 🦅

**Comment by Scarlaid** [comment]
closing this because I updated the whole pack to 1.20.1 now
