### ISSUE TITLE
bro loves to post random mods here

### ISSUE THREAD

**Issue by VaporeonScripts** [MehVahdJukaar/FastPaintings#15]
![image](https://github.com/user-attachments/assets/db5d8da1-e3da-4d88-a7d9-d70e5fca0a96)

**Comment by MehVahdJukaar** [comment]
yeah lmao. what happens when you copy paste project files an forget to change the publishing ID. Interestingly i didnt even have that mod on modrinth. file been taken down and id fixed

**Comment by VaporeonScripts** [comment]
xD
