### ISSUE TITLE
[1.20.4] NeoForge version doesn't load at all

### ISSUE THREAD

**Issue by FoxMcloud5655** [MehVahdJukaar/FastPaintings#19]
Minecraft version: 1.20.4
NeoForge version: 20.4.237
FastPaintings version: 1.2.9

When loading by itself with no other mods installed (and with other mods, but that shouldn't matter here), the game crashes with exit code 1. No significant logs, no crash report, and no Java crash... The game simply refuses to load.

**Comment by MehVahdJukaar** [comment]
Use 1.20 or 1.21. I don't plan to support that minor version anymore

**Comment by FoxMcloud5655** [comment]
Then since the mod literally breaks modpacks if it's installed, perhaps you should remove it?
