### ISSUE TITLE
Paintings larger than 1x1 are invisible, apart from one block that existed when they were placed

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/FastPaintings#2]
<img width="1512" alt="Screen Shot 2023-07-12 at 13 34 08" src="https://github.com/MehVahdJukaar/FastPaintings/assets/50085439/6ea88de8-b2f4-4321-8bde-cdf52770a38e">

**Comment by thelegitdolt** [comment]
<img width="1512" alt="Screen Shot 2023-07-12 at 13 33 56" src="https://github.com/MehVahdJukaar/FastPaintings/assets/50085439/dad79df2-0d98-41df-a414-0affd3e0c1ae">

**Comment by thelegitdolt** [comment]
Running 1.19.2 forge

**Comment by MehVahdJukaar** [comment]
That's really weird. Can you replicate with just the mod? I never had anything like that must be some incompatibility

**Comment by thelegitdolt** [comment]
ooo yeah i do have. a bunch fo performance stuff

**Comment by MehVahdJukaar** [comment]
Something must be messing with forge model data

**Comment by thelegitdolt** [comment]
i just realized i have an outdated version of moonlight lib on my original instance. I've updated it and everything seems to be fixed. Apologies lol

**Comment by MehVahdJukaar** [comment]
Oh weird it didn't crash on startup
